### PR TITLE
Adds TTL and per domain lexicon delegation

### PR DESCRIPTION
**Pull request by foxwoods369**
Supports multiple domains with their own 'delegated' flag, such as
staging domains that are created separately from the main domain.
TTL was also not passed to lexicon, which could lead to authentication
failures due to stale TXT entries with longer TTLs.

Tested locally with my own staging domain.

### CODE REVIEW

**Comment by foxwoods369** [comment]
Somewhat related: https://github.com/AnalogJ/lexicon/pull/482 which updates the digitalocean provider to use the TTL flag.

**Comment by adferrand** [comment]
Hello @foxwoods369, are you willing to reimplement your PR onto the new stack for dnsrobocert here? It is now coded in Python.

A really good place would be to place the TTL value as a `ttl` parameter in a given DNS provider profile (see https://dnsrobocert.readthedocs.io/en/latest/configuration_reference.html#profiles-section to get a user-side view of what it would be)

If you want to do that, I can provide guidance on how to implement this.

**Comment by foxwoods369** [comment]
Getting back to this now. Looking through the new setup (I'm happy it's in python!), and I'll look into readding this.

**Comment by foxwoods369** [comment]
Quick question: I just followed the developer guide, and poetry install seemed to fail on dns-lexicon. Installing through pip got me unstuck. Known issue?

**Comment by foxwoods369** [comment]
Sorry for the spam; unless I'm mistaken you already added ttl in https://github.com/adferrand/dnsrobocert/commit/3c58a4a168e6a322d4a29508efc7995fb4614c6a? Closing for now, and I'll submit a pull if there is any remaining work I can help with.

**Pull request closed without merging**
