### PR TITLE
Call certonly every time

### PR DESCRIPTION
**Pull request by centja1**
Initial certonly call in main to renew/create certificates was moved to certbot._issue function.  Replaced the code in main and certbot.renew with certbot._issue call

### CODE REVIEW

**Comment by centja1** [comment]
Resolves Issue #730

**Comment by Vertganti** [comment]
I'm sorry for pinging once again but I can see a new release being prepared. So please @adferrand consider merging this PR to fix #730 which affects multiple users. I have tested the fix on one machine and it is working flawlessly.

**Comment by adferrand** [comment]
Yes of course ! Very sorry for the late reply.

**Comment by adferrand** [comment]
OK I look at all the discussion. Indeed it makes sense. Running `certbot certonly` will ensure that the internal configuration of certbot is always in sync with what dnsrobocert is instrumentating overall.

I merge and prepare a release right away.

**Pull request merged**
