### PR TITLE
Added support for arm64 and armhf (armv7) - including the Raspberry Pi

### PR DESCRIPTION
**Pull request by patrickpissurno**
Hi! Please don't merge this pull request.

For the people looking for arm builds of this image, take a look at [my fork](https://github.com/patrickpissurno/rpi-docker-letsencrypt-dns). It's an automated multiarch build of it supporting amd64, arm64 and armhf (armv7).

An up-to-date version of the [upstream source code](https://github.com/adferrand/docker-letsencrypt-dns) is fetched, built and released to my [Docker Hub](https://hub.docker.com/r/patrickpissurno/rpi-docker-letsencrypt-dns) daily (automated via [Travis CI](https://travis-ci.org/patrickpissurno/rpi-docker-letsencrypt-dns/)).

[build status](https://travis-ci.org/patrickpissurno/rpi-docker-letsencrypt-dns)
[](https://hub.docker.com/r/patrickpissurno/rpi-docker-letsencrypt-dns "Click to view the image on Docker Hub")

You just have to replace every `adferrand/letsencrypt-dns` occurrence with `patrickpissurno/rpi-docker-letsencrypt-dns`.

Give it a try!

### CODE REVIEW

**Comment by patrickpissurno** [comment]
So, this PR is more of a discussion than an actual PR. It shouldn't be merged, as I haven't made any changes to the upstream repo at all.

All I did was add a [.travis.yml](https://github.com/patrickpissurno/rpi-docker-letsencrypt-dns/blob/master/.travis.yml) file that integrates with [Travis CI](https://travis-ci.org/patrickpissurno/rpi-docker-letsencrypt-dns). It works just like this:
1. Clones the upstream repo;
2. Builds for amd64, arm64, armhf (armv7);
3. Deploys to [Docker Hub](https://hub.docker.com/r/patrickpissurno/rpi-docker-letsencrypt-dns).

Then I added a cron to Travis so it runs everyday, and thus we have an always up-to-date multiarch image.

How is this `adferrand/letsencrypt-dns` built and deployed at the moment, @adferrand? I mean, what tools? Docker Hub Automated Builds? Some other CI?

It may be possible to keep using whichever tool is in use, but we'd have to ensure it can run Docker CE v19+. I'm using docker's new buildx feature to cross-build things and it is only available from v19 onwards.

One thing about that feature though: it uses QEMU. The good news is we don't need arm servers to run the build. The bad news is it is very slow. And when I say "very", I mean it. It takes about two full hours for it to complete (three archs: amd64, arm64 and armv7).

If you were to switch to Travis CI, it would just be a matter of modifying the .travis.yml file to use the current directory for the build (instead of cloning the upstream repo).

There are some optimizations that I think could be implemented in the future. We could try to figure out a way to enable caching for the builds. Most of the build time is spent doing `wheel` builds from scratch. For example, just `lxml` alone takes 30 minutes or even more (on arm, emulation is to blame). If we could manage to cache those (IMHO, I don't think they need to be rebuilt, except if their versions change), the building process would see a big speed-up.

The biggest reason I think we should try to implement build caching is to reduce wasted CI processing power. I mean, they offer that for free. Two hours worth of processing time for each commit is something. Even if we make it only run once every day, it'd be 60 hours each month. It adds up quickly.

Looking forward to get it working!

**Comment by adferrand** [comment]
Hello again @patrickpissurno!

To respond on how I build the dockers, I use CircleCI. I found the DockerHub autobuild feature very limited, in term of CI/CD functionalities and in term of Docker client functionalities, because the client is in fact something like two years old (what a shame, for DockerHub ...).

Anyway, relying on advanced features in latest Docker client versions is absolutely not a problem for me, quite the opposite.

For the rest of the discussion, I have to say that I had some experiences in multiarch building. Maybe you do not know, put I am part of the Certbot core dev team: through these activities, I refactored in particular with an external contributor the CD process for the official Certbot Docker image. This refactoring involved a multi arch build using QEMU. Relevant repo is https://github.com/certbot-docker/certbot-docker.

Another part of my activity here is about creating the new way to distribute Certbot for Linux, which is through Snap, in implies also to be able to build the snaps for various architectures. And here I invite you to study the current state of my proposition here: https://github.com/basak/certbot-snap-build/pull/27

The general idea is also to setup a QEMU-enabled docker to build "natively" the snap for the target architecture. I hit, like you, the problem of the extremely slow building of wheels for projects with static C libraries (like cryptography, lxml, ...).

I responded to this problem by leveraging the capacity to declare extra indexes for pip. By default, pip will look at sdist packages or wheels in the official repo, PyPI. But you can set (through command line or environment variable) an additional repo to look for the most suitable wheel or sdist of a given dependency. So if you have this kind of extra index that ships with, let's say, cryptography as a pre-build wheel for arm64, then pip will get it instead of the sdist in PyPI, and so avoid the compilation.

This reduces at the extreme the time of the build.

However, using an other extra index in the wild was not sufficient (and to be honest makes me a little uncomfortable to rely on an external system with "untrusted" sources for that critical piece of software). So, the proposition in https://github.com/basak/certbot-snap-build/pull/27 is to push pre-built wheels for each target architecture and each package that is concerned by it to the project GIT repository, send start a local repo during the build, and instruct pip to use it as an extra index.

This way pip will transparently use the local extra index to speed up the build, without invasive procedure (appart a environment variable, the build logic is not change), and also fail safe: if for any reason the local index does not work or do not provide a needed wheel, then pip fallback transparently to build the wheel itself. You just loose the build speed up here, not the build success.

What do you think of that?

**Comment by a16bitsysop** [comment]
A way to speed up the build might to add py3-xxxx packages to alpine for circus dns-lexicon and Certbot if needed like this:

https://git.alpinelinux.org/aports/tree/testing/py3-colour/APKBUILD

Then they can just be added with apk

**Comment by a16bitsysop** [comment]
I tried with travis-ci and the bionic vm already has an old version of docker installed and set up so I changed your script to:

```
before_script:
  - curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
  - docker --version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - df -h
```

This worked to build a simple hello world container with multi arch, I took out the update and upgrade as it didn’t seem to update anything that would help docker and the rest of the build is inside the container.

**Comment by patrickpissurno** [comment]
Well, definitely you guys are well ahead of me in terms of Docker and Python. But based on what you (@adferrand)  said, the solution seems reasonable. Way better than the alternatives.

> and also fail safe: if for any reason the local index does not work or do not provide a needed wheel, then pip fallback transparently to build the wheel itself. You just loose the build speed up here, not the build success.

I really liked the idea of slowing down, but not failing the build. If the build times start to skyrocket, then it's just a matter of taking a look at the logs and figuring out which wheel is to blame.

---

> This worked to build a simple hello world container with multi arch

Great! What about the "experimental" environment variable, still necessary?

It took me quite some time to figure out how to make it all work (trial and error), specially because of those very long build times. So I admit that once I got it working, I didn't spend much time trying to improve it (yet).

One thing to keep in mind (of utmost importance) is the need to use `travis-wait-improved --timeout 240m` when running `docker buildx`. Otherwise, when building wheels that take a long enough amount of time without outputting anything to stdout, Travis will timeout the build and thus fail.

I don't know about other CIs, but it should be compatible.

**Comment by a16bitsysop** [comment]
I copied yours but used language: minimal instead of python as I wasn't using python and it took me a few goes to get it to build as well as I put the environment variables on different lines.

 Yes you need experimental still: [https://docs.docker.com/engine/reference/commandline/buildx_create/](https://docs.docker.com/engine/reference/commandline/buildx_create/)

**Comment by a16bitsysop** [comment]
i just checked and alpine edge has Certbot 1.3:

(1/47) Installing libbz2 (1.0.8-r1)
(2/47) Installing expat (2.2.9-r1)
(3/47) Installing libffi (3.2.1-r6)
(4/47) Installing gdbm (1.13-r1)
(5/47) Installing xz-libs (5.2.4-r0)
(6/47) Installing ncurses-terminfo-base (6.2_p20200308-r0)
(7/47) Installing ncurses-libs (6.2_p20200308-r0)
(8/47) Installing readline (8.0.4-r0)
(9/47) Installing sqlite-libs (3.31.1-r1)
(10/47) Installing python3 (3.8.2-r0)
(11/47) Installing py3-ordered-set (3.1.1-r0)
(12/47) Installing py3-appdirs (1.4.3-r2)
(13/47) Installing py3-parsing (2.4.6-r1)
(14/47) Installing py3-six (1.14.0-r1)
(15/47) Installing py3-packaging (20.3-r0)
(16/47) Installing py3-setuptools (46.0.0-r0)
(17/47) Installing py3-cparser (2.20-r0)
(18/47) Installing py3-cffi (1.14.0-r0)
(19/47) Installing py3-idna (2.9-r0)
(20/47) Installing py3-asn1crypto (1.3.0-r0)
(21/47) Installing py3-cryptography (2.8-r1)
(22/47) Installing py3-openssl (19.1.0-r0)
(23/47) Installing py3-josepy (1.3.0-r0)
(24/47) Installing py3-pbr (5.4.4-r0)
(25/47) Installing py3-mock (2.0.0-r6)
(26/47) Installing py3-tz (2019.3-r2)
(27/47) Installing py3-pyrfc3339 (1.1-r3)
(28/47) Installing py3-chardet (3.0.4-r3)
(29/47) Installing py3-certifi (2019.11.28-r0)
(30/47) Installing py3-urllib3 (1.25.8-r0)
(31/47) Installing py3-requests (2.23.0-r0)
(32/47) Installing py3-requests-toolbelt (0.9.1-r1)
(33/47) Installing py3-acme (1.0.0-r0)
(34/47) Installing py3-configargparse (0.15.2-r0)
(35/47) Installing py3-configobj (5.0.6-r7)
(36/47) Installing py3-distro (1.4.0-r3)
(37/47) Installing py3-distutils-extra (2.43-r0)
(38/47) Installing py3-future (0.18.2-r0)
(39/47) Installing py3-parsedatetime (2.5-r0)
(40/47) Installing py3-zope-interface (4.7.2-r0)
(41/47) Installing py3-zope-proxy (4.3.3-r0)
(42/47) Installing py3-zope-deferredimport (4.3.1-r2)
(43/47) Installing py3-zope-deprecation (4.4.0-r3)
(44/47) Installing py3-zope-event (4.4-r4)
(45/47) Installing py3-zope-hookable (5.0.1-r0)
(46/47) Installing py3-zope-component (4.6-r0)
(47/47) Installing certbot (1.3.0-r0)

It has a v20.x Of pip as well as py3-pip

It needs the dns plugins installing with pip as well @adferrand would know if it would work

It would be a start if the apk Certbot could be used

**Comment by a16bitsysop** [comment]
I edited the Dockerfile and timed with apk cerbot and as many py3-xxxx packages I could use, and the original Dockerfile.  They both took the about 24 minutes on an rk3399 arm64 SBC, but there were 2 packages that are taking all the time that don't have py-xxxx versions.  lxml takes 12minutes to install, and pyzmq takes 6 minutes.  If these had py3-xxxx verions added to alpine it should reduce the build time alot.

**Comment by a16bitsysop** [comment]
I have redone the Dockerfile again using just plain Alpine as base and using python that is depended on from the py3-xxxx packages as well as py3-pip and using the pip version of Certbot it hardly compiles anything and builds in a couple of mins.

**Comment by Neejoh** [comment]
I am quite confused in what's going on here, but I'm also very new to this.
So please don't mind me asking;

If I understand correctly DNSroboCert will not "natively" support arm7 for Raspberry PI's, but we're discussing an automated build process of a fork that is of the now-deprecated `adferrand/letsencrypt-dns`?

Is there something I can do now to get certificates up and running? Tried running it with the following command, but that gives me errors that `@example.com` is forbidden. I think it doesn't read the `config.yml` that I've set up. Should I convert my "new" config back to how #16 is set up (I also have TransIP as DNS provider).

```
sudo docker run --rm \
    -v /opt/dnsrobocert/config.yml:/etc/dnsrobocert/config.yml \
    -v /etc/letsencrypt:/etc/letsencrypt \
    patrickpissurno/rpi-docker-letsencrypt-dns
```

Also, I have all my persistent data for all my containers in `/opt`, am I doing the volumes right? 
```
-v /path/on/host/config.yml:/etc/dnsrobocert/config.yml
```
Or should they be switched around?  The [Docker Volumes docs](https://docs.docker.com/storage/volumes/) doesn't really help a newbie like me out here.

**Comment by a16bitsysop** [comment]
You can build your own docker image from the Dockerfile, or just install it with pip as it’s in the PyPi repository now. I started writing an alpine one:

```
FROM alpine:3.11

RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories \
&& apk add --no-cache py3-pip py3-cryptography py3-lxml py3-future py3-zope-proxy && pip3 install dnsrobocert \
&& mkdir -p /etc/letsencrypt

CMD [ "sh", "-c",  "dnsrobocert -c '${CONFIG_PATH} -d ${CERTS_PATH}'" ]
```

It uses ‘native’ python packages for the ones take a long time to build on a pi

**Comment by adferrand** [comment]
Yes very sorry @Neejoh, you just arrived at the moment I made a major refactoring, and moved from `adferrand/letsencrypt-dns` to `adferrand/dnsrobocert`.

The Dockerfile from @a16bitsysop seems very decent to me. You can use it if you are willing to build the docker image by yourself.

**Comment by Neejoh** [comment]
@adferrand I kind of figured as much.

I would love to give that Docker file a try but I'm afraid I'm a bit too new to this all.
Installed a Home Assistant Docker last week through their step-by-step tutorial, that's about how much I know about Docker.
I was hoping to start with DNSroboCert as base, then install a NGINX reverse proxy Docker image to make some of my network tools available to the outside, but only over HTTPS.

If you guys can point me into the right direction on where/how to run the code by @a16bitsysop to build the Docker file myself, that would be much appreciated. I'll get out of this issue and leave you guys talking about actual issue-related stuff 😉

**Comment by a16bitsysop** [comment]
It looks like there is a test multi arch image now!

**Comment by adferrand** [comment]
Yes @a16bitsysop, based on your work for the Dockerfile and @patrickpissurno for the orchestrated build with buildx, I am preparing the multi arch development. The `test` tag corresponds to dnsrobocert 3.0.2, you can test it, @Neejoh too.

**Comment by a16bitsysop** [comment]
Great, are you going to expand to all the alpine supported architectures? I adapted @patrickpissurno travis builds into my own Docker images now as I was struggling with docker and diy before! Will be using the ‘native’ python way in one of my own Dockerfiles as well :-)

**Comment by Neejoh** [comment]
That would be awesome, would love to test it. 

Can you nudge me in the right direction; do I have to build this release on my Pi with a specific command, then use a local path  to that image in `docker-composer.yml`?

I feel like my lack of knowledge is not particularly well placed here in this issue, but if I can test anything I'll gladly do so. If there is a better place for my questions please let me know (Discord, Slack or anything like that).

**Comment by a16bitsysop** [comment]
sudo docker run --rm \
    -v /opt/dnsrobocert/config.yml:/etc/dnsrobocert/config.yml \
    -v /etc/letsencrypt:/etc/letsencrypt \
    adferrand/dnsrobocert:test

**Comment by adferrand** [comment]
Ok guys. The work made here was almost everything needed. So I took the time to implement that.

I just published DNSroboCert 3.1.0, that ships with a multi-arch Docker image. Architectures supported are all architectures available with the official `alpine` docker.

You can see here the new Docker image with the architectures supported for `latest` and `3.1.0` tags: https://hub.docker.com/r/adferrand/dnsrobocert/tags.

@Neejoh you have almost nothing to do. Just pull the latest version of `adferrand/dnsrobocert`, your docker client will get the appropriate architecture flavor for you.

**Comment by a16bitsysop** [comment]
Great, thanks

**Comment by Neejoh** [comment]
Happy to say that it starts and is up and running. Really awesome job guys.

Haven't gotten my certificate for my domain yet though.
It keeps telling me there is no TXT record, even though I see the record
has been made (and later being cleaned up) in my DNS zone.
I've set the sleep_time to 90 with 5 retries, should I just keep upping
this until it is resolved?

Again, great work getting it working, much appreciated.

**Comment by a16bitsysop** [comment]
What are your dns settings?  Are you using your ISP or google or 1.1.1.1/cloudflare etc

**Comment by Neejoh** [comment]
Got it to work eventually.
Had to up the sleep_time to 120, then it had time enough to validate them.

**Pull request closed without merging**
